# Generated by Django 4.2.20 on 2025-04-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre',
            name='categorie',
            field=models.CharField(choices=[('INFORMATIQUE', 'Informatique'), ('MARKETING', 'Marketing'), ('RESSOURCES_HUMAINES', 'Ressources Humaines'), ('FINANCE', 'Finance'), ('AUTRE', 'Autre')], default='AUTRE', max_length=50),
        ),
        migrations.AddField(
            model_name='offre',
            name='exigences',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offre',
            name='experience_requise',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='offre',
            name='localisation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='offre',
            name='niveau_etude',
            field=models.CharField(blank=True, help_text='Ex : Bac+3, Bac+5, Master, Doctorat, etc.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='offre',
            name='salaire',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='offre',
            name='type_contrat',
            field=models.CharField(blank=True, choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('Stage', 'Stage'), ('Freelance', 'Freelance'), ('Alternance', 'Alternance')], max_length=50, null=True),
        ),
    ]
