# Generated by Django 4.2.20 on 2025-04-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec', '0002_offre_categorie_offre_exigences_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='email',
            field=models.EmailField(default='default', max_length=191, unique=True),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='mot_de_passe',
            field=models.CharField(default='default', max_length=128),
        ),
    ]
