# Generated by Django 4.2.20 on 2025-05-07 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rec", "0003_entreprise_email_entreprise_mot_de_passe"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="candidat",
            options={"verbose_name": "Candidat", "verbose_name_plural": "Candidats"},
        ),
    ]
