# Generated by Django 4.2.20 on 2025-05-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec', '0004_alter_candidat_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='default', max_length=191, unique=True)),
                ('mot_de_passe', models.CharField(default='default', max_length=128)),
            ],
        ),
    ]
